### ISSUE TITLE
Have loading overlay when adding/removing polls/questions, as well as login

### ISSUE THREAD

**Issue by IxLahiji** [SyncEDorg/Pollo#47]

**Comment by AtriLahiji** [comment]
Here's something you could use: https://vuetifyjs.com/en/components/progress-circular

**Comment by AtriLahiji** [comment]
Also for learning resources:
https://www.youtube.com/watch?v=IkrbIFZz_IM
https://www.youtube.com/watch?v=sYIUkTap1ds

Let me know and I can walk you through what has changed since you last worked on this.

**Comment by AtriLahiji** [comment]
I tried loading, but this seemed like it would require far too many core changes at the moment. My solution for now is to warm up all required cloud functions on first load. Cloud function invocations are dirt cheap and all projects get the first 2,000,000 free, so this should not be a concern. A poll with 300 students would only use up 1% of the free usage so using them liberally won't be an issue.
