### ISSUE TITLE
Implement short answer questions

### ISSUE THREAD

**Issue by AtriLahiji** [SyncEDorg/Pollo#97]

**Comment by AtriLahiji** [comment]
@IxLahiji Could you check out this branch and see if it works well? Any suggestions?

**Comment by IxLahiji** [comment]
So, here's a few issues I've found.

1. It updates with whatever the user is typing, even in progress. It seems to update every time the textbox is updated. This kinda makes the "submit" button kinda useless. You can watch this happening on the real-time responses for the question.

2. There doesn't seem to be feedback on whether a user's answer has been submitted or not. This is actually true for all questions, but I just noticed it more with this type of question

3. It doesn't stack the same answers. For example, if two people write the word "Dog" it just writes both "Dog"s in the real-time answers. It'd be better if the answers would be stacked, then have an indicator for how many people said that particular answer. 
I know this poses a few problems, for instance do we normalise text to keep it consistent? But I would say don't worry about those details yet, and we'll address them as necessary. I've seen Other polling software have cases where "dog" and "Dog" would show up as different answers, which is fine.
